### ISSUE TITLE
Feat(test-stage): Request to add chaos stage to test coreDNS application

### ISSUE THREAD

**Issue by rajdas98** [crosscloudci/coredns-configuration#41]
Motivation:
- Requesting a chaos stage which will contain coreDNS's test cases
- Adding Litmus coreDNS pod delete experiment to check the resiliency of the coreDNS application

Approach:
  - Using KIND (Kubernetes In Docker) cluster to run the experiment
  - Replace the image with the latest build image
  - Installing Litmus dependencies on the KIND cluster
  - Installation of coreDNS pod delete experiment- https://hub.litmuschaos.io/charts/coredns/experiments/coredns-pod-delete
  - The experiment's workflow - https://github.com/litmuschaos/litmus/blob/master/experiments/coredns/pod_delete/activity_diagram_coredns.png
  - The pipeline runs successful based on the experiment's verdict

**Comment by agentpoyo** [comment]
This appears to have been merged.
